name: Deploy Landing Page

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * THU"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: x-access-token:${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
